#!/usr/bin/ruby

files = Dir["*"]

files.each do |fl|
    ext = fl.downcase.split(".").pop
    name = fl.downcase.split(".").shift
    next if ext != "jpg"

    `jpegtran -copy none -optimize -progressive -outfile #{name}_min.jpg #{name}.jpg`

    `rm #{name}.jpg`
    `mv #{name}_min.jpg #{name}.jpg`

end
